const CART_CONSTANT = {
  CART_ADD_ITEM: 'CART_ADD_ITEM',
  CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
  CART_SAVE_SHIPPING_ADDRESS: 'CART_SAVE_SHIPPING_ADDRESS',
  CART_ITEMS_RESET: 'CART_ITEMS_RESET'
};

export default CART_CONSTANT;
